server:
  port: 8082
dubbo:
  application:
    name: impl
  registry:
    address: zookeeper://127.0.0.1:2181
  protocol:
    name: dubbo
    port: 20882

spring:
  datasource:
    driver: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/gou?serverTimezone=UTC
    username: root
    password: 1

logging:
  level:
    com.llm.demo.mapper.*: debug